### PR TITLE
moved to image picker plugin, added support for gallery images

### PR DESCRIPTION
**Pull request by danielgholiof**
After discussion we decided to scrap the current camera and use the image picker plugin. This allows us to use the native camera in the phone and allows for retake of photos, as well as choosing images from gallery. Added an icon for gallery.

### CODE REVIEW

**Comment by DanielWestberg** [comment]
Nice, much easier solution! Maybe the icon furthest to the right should be removed or changed to another one since there are now two identical ones?

**Comment by danielgholiof** [comment]
the icon on the far right is just a placeholder for the filtering icon, are we omitting that feature?

**Comment by DanielWestberg** [comment]
I think most of the filtering will be done in the statistics screen, but maybe the user also wants to filter some stuff in the history view, such as specific stores etc. We can leave it for now, maybe set it to "filter_alt" instead of "filter".

**Comment by dangho1** [comment]
done and dusted

**Pull request merged**
