### PR TITLE
added cleaning function for receipts

### PR DESCRIPTION
**Pull request by kakann**
Can now clean receipts using cleanReceipt function in utils.

The function does four things:

1) If an item in a receipt has been replaced with "kr/kg" it gets the actual item name
2) If an item is a discount item (item name = "rabatt", "prisnersättning" etc that item is concatenated with the item above.
3) removes all items with some stopwords in it (for example "kortköp" 
4) Removes all items which only includes numbers, which is usually not a real item but a missinterpretation of the receipt data.

Rules and additional stopwords can easily be added.

### CODE REVIEW

**Comment by DanielWestberg** [comment]
Hasn't this functionality already been implemented in pr #138?

**Comment by kakann** [comment]
> Hasn't this functionality already been implemented in pr #138?

True, my bad, thought I was assigned that task. However, this cleaning function does abit more aswell

**Comment by kakann** [comment]
> Hasn't this functionality already been implemented in pr #138?

This is more #145 .

**Comment by danielgholiof** [comment]
Merged into #148 bre

**Pull request closed without merging**
